#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RUN-CMD $ KARL SANDWICH
description: > 
  Software developer, drone crasher, recovering maker,
  occasional gamer, faux tographer, avid indoorsman.
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tr0nk
github_username:  RUN-CMD
thingiverse_username: sandwich
tinkercad_username: 1oyJZCjgl5d-sandwich

# Build settings
markdown: kramdown
